op-program-base TAG='op-program-base:latest':
    docker buildx build -f ../../../../chain/op-program/Dockerfile.repro --target=src -t {{TAG}} ../../../../chain

op-program-svc TAG='op-program-svc:latest': op-program-base
    docker buildx build -f Dockerfile -t {{TAG}} .
