name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: lint
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - name: Install components
        run: |
          rustup component add rustfmt clippy
          cargo install cargo-machete --version 0.8.0
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Check clippy
        run: cargo clippy --locked -- -D warnings
      - name: Check deps
        run: cargo machete
  test:
    name: test
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - uses: extractions/setup-just@v2
        with:
          just-version: 1.40.0
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Install kurtosis
        run: |
          sudo apt-get install jq
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt remove kurtosis-cli
          sudo apt install kurtosis-cli=1.11.1 -V
          docker system prune
      - name: Prepare optimism
        run: make chain
      - name: Start optimism
        run: |
          make devnet-up
          make set-port
          make get-l1-config
      - name: Start preimage server
        run: make server-up &
      - name: Wait for chain to get ready
        run: make wait
      - name: Test
        run: make test